export const VALIDATION_KEY = {
  EMAIL_INVALID: 'EMAIL_INVALID',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  SLUG_INVALID: 'SLUG_INVALID',
  RUBRIC_WEIGHTS: 'RUBRIC_WEIGHTS',
  DEFECTS_REQUIRED: 'DEFECTS_REQUIRED',
} as const;

export type ValidationKey = (typeof VALIDATION_KEY)[keyof typeof VALIDATION_KEY];
